[project]
name = "MyAwesomeGame"
version = "1.0.0"
display_version = "1.0-beta"
author = "YourName Studio"

[package]
# If want to customize specific package name, go to runtime/client/[platform]/config.toml, it will override this.
package_name = "com.yourstudio.myawesomegame"
# It will auto add perfix like .app or .exe
executable_name = "MyAwesomeGame"

[plugins]
enabled = [
    "core-math-utils",
    "phys-jolt-physics",
    "feat-ai-vision"
]

[plugins.platform_extra]
ios = ["plt-ios-arkit"]
android = ["plt-android-sensors"]

[build]
obfuscate_python = false
asset_compression = 6
icon_path = "assets/branding/icon.png"

# --- GLOBAL RENDERING STRATEGY ---
[rendering]
#default = "render-vulkan"
#fallback = ["render-gles3"]
vsync = true
msaa = 4

# --- WINDOWS OVERRIDES ---
[platforms.windows.rendering]
# Windows users prefer DX12 for performance/RayTracing
default = "render-dx12"
fallback = ["render-vulkan", "render-dx11"]

# --- IOS OVERRIDES ---
[platforms.ios.rendering]
# iOS ONLY supports Metal
default = "render-metal"
fallback = []
msaa = 2  # Lower MSAA to save battery on mobile

# --- ANDROID OVERRIDES ---
[platforms.android.rendering]
# Most modern Androids are Vulkan, but fallback is critical
default = "render-vulkan"
fallback = ["render-gles3"]

[metadata]
# config version,dont modify
version = 1.0